sudo: required

language: bash

services:
- docker

before_install:
- docker pull alpine
- docker run alpine /bin/ash -c "cd /root && wget https://raw.githubusercontent.com/thde/seedy/master/seedy.sh && chmod +x seedy.sh"

script:
- docker run alpine /bin/ash -c "cd /root && ./seedy.sh"
